apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: {{ .Values.userservice.replicaCount }}
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
        - name: users
          image: {{ .Values.userservice.image }}
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-config-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: user-service-config-secret
                  key: DB_PASS
            - name: JWT_SALT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: JWT_SALT
          ports:
            - containerPort: {{ .Values.userservice.service.port }}
              name: web
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service-app
  ports:
    - protocol: TCP
      port: {{ .Values.userservice.service.port }}
      targetPort: web
      name: web
  type: {{ .Values.userservice.service.type }}

